### ISSUE TITLE
Change current working directory before running

### ISSUE THREAD

**Issue by RobLoach** [phpzone/shell#5]
``` yaml
extensions:
    PhpZone\Shell\Shell:
        list:
            description: List all find in the beep/boop directory
            script:
                - ls *
            cwd: beep/boop
```
